
task:
  name: debian (py2 check root)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python2
    dev/system-info
    eatmydata make -j6 PYTHON=python2 check

task:
  name: debian (py2 long-check)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python2
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python2 long-check"

task:
  name: debian (py2 check)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python2
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python2 check"

task:
  name: debian (py3 check root)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    dev/system-info
    eatmydata make -j6 PYTHON=python3 check

task:
  name: debian (py3 long-check)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python3 long-check"

task:
  name: debian (py3 check)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python3 check"

task:
  name: freebsd (py3 check)
  freebsd_instance:
    image: freebsd-12-2-release-amd64
    cpu: 4
    memory: 4
  script: |
    set -xe
    dev/prep-for-freebsd-build python3
    dev/system-info
    gmake -j6 PYTHON=python3.7 check

task:
  name: macos (py3 check)
  osx_instance:
    image: catalina-base
  script: |
    set -xe
    dev/prep-for-macos-build python3
    export PKG_CONFIG_PATH=/usr/local/opt/readline/lib/pkgconfig
    export PYTHON=python3
    dev/system-info
    make -j4 PYTHON=python3 check
